CREATE TABLE [dbo].[AGENTS]
(
	[AGENT_CODE] INT NOT NULL  IDENTITY(1,1), 
    [AGENT_NAME ] NVARCHAR(MAX) NOT NULL, 
    [WORKING_AREA ] NVARCHAR(MAX) NOT NULL, 
    [COMMISSION] DECIMAL(18, 3) NOT NULL, 
    [PHONE_NO] NVARCHAR(MAX) NOT NULL, 
    [COUNTRY] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [PK_AGENTS] PRIMARY KEY ([AGENT_CODE]),
    CONSTRAINT [FK_AGENTS_CUSTOMER] FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[CUSTOMER]([AGENT_CODE]), 
    CONSTRAINT [FK_AGENTS_ORDERS] FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[ORDERS]([AGENT_CODE]), 
    
  
)
