CREATE TABLE [dbo].[CUSTOMER]
(
	[CUST_CODE] INT NOT NULL IDENTITY(1,1), 
    [CUST_NAME] NVARCHAR(MAX) NOT NULL, 
    [CUST_CITY] NVARCHAR(MAX) NOT NULL, 
    [WORKING_AREA] NVARCHAR(MAX) NOT NULL, 
    [CUST_COUNTRY] NVARCHAR(MAX) NOT NULL, 
    [GRADE] INT NOT NULL, 
    [OPENING_AMT] DECIMAL(18, 3) NOT NULL, 
    [RECEIVE_AMT] DECIMAL(18, 3) NOT NULL, 
    [PAYMENT_AMT] DECIMAL(18, 3) NOT NULL, 
    [OUTSTANDING_AMT] DECIMAL(18, 3) NOT NULL, 
    [PHONE_NO] NVARCHAR(MAX) NOT NULL, 
    [AGENT_CODE] INT NOT NULL UNIQUE, 
    CONSTRAINT [PK_CUSTOMER] PRIMARY KEY ([CUST_CODE]),
    CONSTRAINT [FK_CUSTOMER_ORDERS] FOREIGN KEY ([CUST_CODE]) REFERENCES [dbo].[ORDERS]([CUST_CODE]) , 
    
)
