CREATE TABLE [dbo].[ORDERS]
(
	[ORD_NUM] INT NOT NULL IDENTITY(1,1), 
    [ORD_AMOUNT] DECIMAL(18, 3) NOT NULL, 
    [ADVANCE_AMOUNT] DECIMAL(18, 3) NOT NULL, 
    [ORD_DATE] DATE NOT NULL, 
    [CUST_CODE] INT NOT NULL UNIQUE, 
    [AGENT_CODE] INT NOT NULL UNIQUE, 
    [ORD_DESCRIPTION] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [PK_ORDERS] PRIMARY KEY ([ORD_NUM]),
    
)
