//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBeNTITI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CURSOS()
        {
            this.INSCRITO = new HashSet<INSCRITO>();
        }
    
        public int COD { get; set; }
        public string nombre { get; set; }
        public string fecha_inicio { get; set; }
        public string duracion { get; set; }
        public string valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRITO> INSCRITO { get; set; }
    }
}
