CREATE TABLE [dbo].[INSCRITO]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Id_Alumno] INT NOT NULL, 
    [COD_CURSO] INT NOT NULL, 
    CONSTRAINT [FK_INSCRITO_Alumno] FOREIGN KEY ([Id_Alumno]) REFERENCES [ALUMNO]([Id]), 
    CONSTRAINT [FK_INSCRITO_Curso] FOREIGN KEY ([COD_CURSO]) REFERENCES [CURSOS]([COD]), 
    
)
